### ISSUE TITLE
file telegraf.conf?

### ISSUE THREAD

**Issue by serpap79** [vikramjakhr/telegraf-solaris#1]
Quizás quisiste decir: Hola. Indicas copiar el fichero /config/telegraf.conf, pero no está en el paquete. ¿Podrías subirlo? Muchas gracias. Saludos.
131/5000
Hi.

You indicate to copy the file /conf/telegraf.conf, but it is not in the package.

Could you upload it?

Thank you.

Greetings.

**Comment by vikramjakhr** [comment]
Hi, Thanks for pointing out the issue.

I've uploaded the sample telegraf config in the repository for now, below is the download URL for that.
[https://raw.githubusercontent.com/vikramjakhr/telegraf-solaris/master/conf/telegraf.conf](https://raw.githubusercontent.com/vikramjakhr/telegraf-solaris/master/conf/telegraf.conf)

I'll update the release soon.

**Comment by vikramjakhr** [comment]
I've updated the release also with the conf.

[https://github.com/vikramjakhr/telegraf-solaris/releases/latest](https://github.com/vikramjakhr/telegraf-solaris/releases/latest)
