### ISSUE TITLE
CPU Stats - Always idle

### ISSUE THREAD

**Issue by marknmel** [vikramjakhr/telegraf-solaris#2]
Hey @vikramjakhr  - 
First - thanks for this.  It's nice to see telegraf for Solaris after so long!

I've found a quirk though. (and I'm new to golang, so I'm opening this as an issue - perhaps you can help out)...

In Solaris - when running _vmstat -S_ you get output like this:

```# vmstat -S
 kthr      memory            page            disk          faults      cpu
 r b w   swap  free  si  so pi po fr de sr s5 s6 s3 s3   in   sy   cs us sy id
 0 0 0 6616104 3583704 0  0  0  0  0  0  0  1  1  0  0  308  692  219  0  0 99
```
From the Solaris man page - example: [link](http://ibgwww.colorado.edu/~lessem/psyc5112/usail/man/solaris/vmstat.1.html)
> Without options, vmstat displays a one-line summary  of  the virtual  memory  activity  since  the system was booted.

This is the issue, as telegraf reports my system as idle, when it certainly isn't.

As a sysadmin, interactively I'd run:

```
# vmstat -S 1 2
 kthr      memory            page            disk          faults      cpu
 r b w   swap  free  si  so pi po fr de sr s5 s6 s3 s3   in   sy   cs us sy id
 0 0 0 6615624 3583240 0  0  0  0  0  0  0  1  1  0  0  308  732  219  0  0 99
 10 0 0 3413680 424808 0  0  0  0  0  0  0  0  0  0  0  654 251989 1127 62 38 0
```
...and just use the second result.  It's lost on me on how to do this in golang.  

I do have a dev environment set up, and I see some of the shortcomings with the port - but I'd like to help out where I can.

Can you help me out on this one please?
Thanks!!

**Comment by vikramjakhr** [comment]
Hi, Thanks for using telegraf-solaris.

 I don't have solaris system for now to test. It was created for one of the client. 
But still you can modify the below file for this and build it again.

https://github.com/vikramjakhr/telegraf-solaris/blob/master/i_cpu.go

![image](https://user-images.githubusercontent.com/10959156/58758019-e2b6ca80-8532-11e9-9188-45c401e33fec.png)
Change the above line with 
`output, err := exec.Command("vmstat", "-S", "1", "2").CombinedOutput()`

And after this also change the below
![image](https://user-images.githubusercontent.com/10959156/58758035-290c2980-8533-11e9-9e75-f30d8abaf46a.png)
to 
`values:= strings.Fields(rows[2])`

Hope that will work.

**Comment by vikramjakhr** [comment]
@marknmel I also got the same issue earlier, had that code in separate branch. 

I've merged the fix now in master branch https://github.com/vikramjakhr/telegraf-solaris/pull/4

You can try build the binary now.
