### ISSUE TITLE
Not able to get telegraf running on Solaris 11

### ISSUE THREAD

**Issue by adityask2** [vikramjakhr/telegraf-solaris#6]
Hi,
I followed the steps mentioned in wiki. However, Im not able to get telegraf running.

ERROR - bash: /usr/bin/telegraf: Invalid argument

OS used - Solaris 11 - SunOS solaris 5.11 11.4.0.15.0 i86pc i386 i86pc
gcc version - 7

On starting telergaf - /etc/init.d/telegraf start
console says "Starting Telegraf agent". However, on checking for its status, its not running.

**Comment by vikramjakhr** [comment]
@adityask2 You might be missing telegraf configuration(/etc/telegraf/telegraf.conf). 

Could you please share some more details.
* output of /etc/init.d/telegraf status 
* telegraf config file (/etc/telegraf/telegraf.conf)
* logs if any

**Comment by adityask2** [comment]
Thanks for the quick response. Highly appreciated :)

output of /etc/init.d/telegraf status -- telegraf not runnng
output of /var/log/telegraf/telegraf.log -- bash: /usr/bin/telegraf: Invalid argument

Uploading the telegraf-conf file. Using the default one. 


[telegraf-conf.txt](https://github.com/vikramjakhr/telegraf-solaris/files/3642286/telegraf-conf.txt)

**Comment by vikramjakhr** [comment]
Is your influxDB is running?

In config it defaults localhost:8086

[[outputs.influxdb]]
  urls = ["http://localhost:8086"] # required
  database = "telegraf" # required
  retention_policy = ""
  write_consistency = "any"
  timeout = "5s"
  content_encoding = "gzip"

**Comment by adityask2** [comment]
I didnt have the influxdb running. However, I changed the output plugin to file writer. But getting the same error. I tried to run the telegraf standalone (as in not as a service) using command - telegraf --config <path to config> --test. Even then getting the same error. 

I think something at fundamental (prerequisites) level is missing.

I have gcc at verion 7. However, I see there is also gccgo compiler. Should i install it explicitly since gcc 7 comes with gccgo compiler also.

**Comment by adityask2** [comment]
Should I have gccgo compiler installed on my solaris machine? Since I already have gcc 7 version. 
https://golang.org/doc/install/gccgo

**Comment by vikramjakhr** [comment]
@adityask2 Is it possible for you to give me access to the server?

**Comment by adityask2** [comment]
@vikramjakhr  The machine is in private network. So, it wouldn't be possible. However, I can give you any environment details that you require.

**Comment by vikramjakhr** [comment]
@adityask2 Could you try building the binary from source using gcc7.

Or if it is possible to install Golang than you can build using go also.

**Comment by adityask2** [comment]
Got it working by building the source with go. Thanks :)
